services:
  eventservice:
    build: ./EventService
    container_name: eventservice
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db1:5432/EventService
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db1
    networks:
      - my_network

  tagservice:
    build: ./TagService
    container_name: tagservise
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db2:5432/TagService
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db2
    networks:
      - my_network

  db1:
    image: postgres:13
    container_name: db1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=EventService
    ports:
      - "5433:5432"
    networks:
      - my_network

  db2:
    image: postgres:13
    container_name: db2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=TagService
    ports:
      - "5434:5432"
    networks:
      - my_network


networks:
  my_network:
    driver: bridge
