spring:
  cloud:
    gateway:
      routes:
        - id: image-service
          uri: lb://IMAGESERVICE
          predicates:
            - Path=/image/**


        - id: event-service
          uri: lb://EVENTSERVICE
          predicates:
            - Path=/all

        - id: event-service1
          uri: lb://EVENTSERVICE
          predicates:
            - Path=/event/**
          filters:
            - AuthenticationFilter

        - id: tag-service
          uri: lb://TAGSERVICE
          predicates:
            - Path=/tag/**
            - Path=/tag
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**

        - id: image-service
          uri: lb://IMAGESERVICE
          predicates:
            - Path=/image/**

application:
  name: SWIGGY-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
